### ISSUE TITLE
2.4 - Opcije korisnika

### ISSUE THREAD

**Issue by Dr-Samardzic** [Dr-Samardzic/PI-Projekt#14]
- [ ] Pretraziti prijatelje
- [ ] Profil
- [ ] Grupiranje prijatelja
- [ ] Dodavanje darova u wish list

**Comment by Dr-Samardzic** [comment]
Moramo dodati sve opcije korisnika u obliku check liste tako da znamo di smo zapeli

**Comment by Dr-Samardzic** [comment]
- [ ] Pretraziti prijatelje

**Comment by PauloSuljic** [comment]
Unnecessary issue
