### ISSUE TITLE
3.3 - Korisnicke opcije

### ISSUE THREAD

**Issue by Dr-Samardzic** [Dr-Samardzic/PI-Projekt#9]
- [ ] Pretraziti prijatelje
- [ ] Profil
- [ ] Grupiranje prijatelja
- [ ] Dodavanje darova u wish list

**Comment by Dr-Samardzic** [comment]
Dodao jos jedan feature. Provjera postojeceg imena pri registraciji

**Comment by PauloSuljic** [comment]
Should be deleted
